eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.250:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: PRODUCTER
    api-b:
      path: /api-b/**
      serviceId: CLIENT